### PR TITLE
New options handling

### PR DESCRIPTION
**Pull request by inducer**

### CODE REVIEW

**Comment by inducer** [comment]
NB: This currently fails to import with
```
/usr/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_metis.py:28: in <module>
    import pymetis
../pymetis/__init__.py:28: in <module>
    from pymetis._internal import Options
E   ImportError: AttributeError: NUMBERING
```
when exactly the same method seems to work OK in PyOpenCL:

https://github.com/inducer/pyopencl/blob/0195ba6ab8d5fefddf8907820120c9db2c312527/src/wrap_constants.cpp#L156-L179

**Comment by nishraptor** [comment]
What can I do to help with this? I was planning on just adding a seed option like the other options, but this would be a good solution to add any options. I've pulled the branch but not sure how I can help

**Comment by inducer** [comment]
I think the task now would be to actually get it to work: expose the option constants and fix the options passing of the functions to use this new mechanism, update the docs, and add some tests. Do this, or some part of it, stick it in a PR, and I'd call that progress.

**Comment by nhartland** [comment]
I had a shot at understanding the error here but didn't make any progress.
Is it even clear where exactly that AttributeError is thrown?

**Comment by inducer** [comment]
Thanks for giving this a look. I believe the error is being thrown from [this line](https://github.com/inducer/pymetis/blob/3e02f5304d505b05d37fe3014742fcf82358f3b5/src/wrapper/wrapper.cpp#L236), specifically the `.attr` in [this macro](https://github.com/inducer/pymetis/blob/3e02f5304d505b05d37fe3014742fcf82358f3b5/src/wrapper/wrapper.cpp#L234).

**Comment by nhartland** [comment]
That part seems to compile fine though. I tried rewriting it a few different ways (with/without macro) to no effect. 
Indeed removing it stops the error on import though.

**Comment by inducer** [comment]
I think I made some progress. af76cad gets option setting/getting to work AFAICT.

**Comment by nhartland** [comment]
Seems to work! Thanks! I can have a shot at wiring up the options and testing them.

What would be the mechanism for passing the pymetis.Options python object back to C++? Something like adding a
```const py::object &options_py``` to the signature of `wrap_part_graph` and then casting back to a `metis_options` class with `py::cast` or is there a simpler way?

**Comment by inducer** [comment]
See 406d0f4.

**Comment by inducer** [comment]
Superseded by #31, I think.

**Pull request closed without merging**
