### PR TITLE
document minimal partitioning example w/pictures

### PR DESCRIPTION
**Pull request by AlDanial**
Although I've used metis before, it took me a bit of digging around to get started with pymetis.  I'm hoping this small documentation contribution will save future users a bit of effort.

### CODE REVIEW

**Comment by AlDanial** [comment]
Couple of notes: 1) the rendered documentation addition with images can be viewed at https://github.com/AlDanial/pymetis.
2) I used drawio to make the images.  If you don't want PNG's in your repo I can add the drawio native XML files which are only  2 kB each, but that adds a dependency on drawio plus adds a step to convert the XML to an image format.

**Comment by inducer** [comment]
Thanks for your contribution! This looks great. I think I would like to have the XML files in addition to the PNGs. That way, if they need to be changed for some reason, the diagrams don't need to be redrawn from scratch.

**Comment by AlDanial** [comment]
I went to verify that the online version of drawio can read the two files and found drawio has been rebranded, is now diagrams.net.  In any event, https://app.diagrams.net/ can read the files just fine.

**Comment by inducer** [comment]
Thanks!

**Comment by AlDanial** [comment]
oops, a typo of duplicate lines in ``README.rst``:
<pre>
pymetis.part_graph(2, adjacency=adjacency_list)
n_cuts, membership = pymetis.part_graph(2, adjacency=adjacency_list)
</pre>
should just be
<pre>
n_cuts, membership = pymetis.part_graph(2, adjacency=adjacency_list)
</pre>
I can make a new PR, but seems a bit much to delete one line.

**Comment by inducer** [comment]
Thanks! 20c307181bf9936eb014d918e8835145da659059

**Pull request merged**
